name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'github token'
    required: false
    default: ''
  ucsmetadata:
    description: 'U-CS metadata spec'
    required: false
    default: ''
  eksmetadata:
    description: 'U-CS eks metadata spec'
    required: false
    default: ''
outputs:
  eksmeta:
    description: 'EKS metadata'
runs:
  using: 'node16'
  main: 'dist/index.mjs'