name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'github token'
    required: false
    default: ''
  ucsmetadata:
    description: 'U-CS metadata spec'
    required: false
    default: ''
  eksmetadata:
    description: 'U-CS eks metadata spec'
    required: false
    default: ''
  eksrunner:
    description: "workflow to run for eks deployments"
    required: true
    default: "deploy_eks.yml"
outputs:
  eksmeta:
    description: 'EKS metadata'
runs:
  using: node16
  main: dist/index.js